### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by max-bp** [mrbrainz/Mixcloud-Tracklist-Enabler#2]
Hi mrbrainz!
I continued developing your script, keeping it up to date, and added some useful tools to it!
_Thank you for creating the original code!_

https://github.com/max-bp/New-Mixcloud-Tracklist-Enabler

**Comment by mrbrainz** [comment]
Hey @max-bp. Great work. It's a shame you just didn't make a pull request on this project. I would have merged it.

**Comment by mrbrainz** [comment]
Merged in mods you made. Works great. Thanks.
